# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-10 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u670d\u52a1\u7f16\u53f7')),
                ('service_name', models.CharField(max_length=50, verbose_name='\u670d\u52a1\u540d\u79f0')),
                ('service_status', models.IntegerField(choices=[(1, '\u542f\u52a8'), (2, '\u672a\u542f\u52a8')], default=1, verbose_name='\u670d\u52a1\u72b6\u6001')),
                ('service_address', models.CharField(default=None, max_length=128)),
            ],
            options={
                'verbose_name': '\u670d\u52a1',
                'verbose_name_plural': '\u670d\u52a1',
            },
        ),
    ]
