# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-10 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsserver', '0002_auto_20170810_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_script',
            field=models.CharField(default=1, max_length=128, verbose_name='\u811a\u672c\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_address',
            field=models.CharField(default=1, max_length=128, verbose_name='\u670d\u52a1\u5730\u5740'),
        ),
    ]
