# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-15 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsserver', '0004_service_service_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_grep',
            field=models.CharField(default=1, max_length=128, null=True, verbose_name='model'),
        ),
    ]
